package com.yilinker.expresspublic.core.contants;

/**
 * Created by Jeico.
 */
public class ApiKey
{
    public static final String ID                                       = "id";
    public static final String FIRST_NAME                               = "first_name";
    public static final String LAST_NAME                                = "last_name";
    public static final String USERNAME                                 = "username";
    public static final String EMAIL_ADDRESS                            = "email_address";
    public static final String CONTACT_NUMBER                           = "contact_number";
    public static final String NEW_CONTACT_NUMBER                       = "new_contact_number";
    public static final String FULL_NAME                                = "full_name";
    public static final String DATE_ADDED                               = "date_added";
    public static final String LAST_DATE_MODIFIED                       = "last_date_modified";
    public static final String PASSWORD                                 = "password";
    public static final String GRANT_TYPE                               = "grant_type";
    public static final String CLIENT_ID                                = "client_id";
    public static final String CLIENT_SECRET                            = "client_secret";
    public static final String ACCESS_TOKEN                             = "access_token";
    public static final String TOKEN_TYPE                               = "token_type";
    public static final String EXPIRES_IN                               = "expires_in";
    public static final String REFRESH_TOKEN                            = "refresh_token";
    public static final String NAME                                     = "name";
    public static final String ADDRESS                                  = "address";
    public static final String LATITUDE                                 = "latitude";
    public static final String LONGITUDE                                = "longitude";
    public static final String BRANCH_ID                                = "branch_id";
    public static final String KEY                                      = "key";
    public static final String CITY                                     = "city";
    public static final String PROVINCE_ID                              = "province_id";
    public static final String KEYWORD                                  = "keyword";
    public static final String OPENING_TIME                             = "opening_time";
    public static final String CLOSING_TIME                             = "closing_time";
    public static final String IMAGE                                    = "image";
    public static final String MESSAGE                                  = "message";
    public static final String DATE                                     = "date";
    public static final String TRACKING_NUMBER                          = "tracking_number";
    public static final String FROM_TO                                  = "from_to";
    public static final String SHIPPING_TYPE                            = "shipping_type";
    public static final String STATUS                                   = "status";
    public static final String STATUS_REMARKS                           = "status_remarks";
    public static final String RIDER_VEHICLE                            = "rider_vehicle";
    public static final String PICKUP_DATE                              = "pickup_date";
    public static final String POUCH_TYPE                               = "pouch_type";
    public static final String ETA                                      = "eta";
    public static final String DELIVERY_STATUS                          = "delivery_status";
    public static final String REGISTRATION_ID                          = "registration_id";
    public static final String LENGTH                                   = "length";
    public static final String WIDTH                                    = "width";
    public static final String HEIGHT                                   = "height";
    public static final String WEIGHT                                   = "weight";
    public static final String PACKAGE_CONTAINER                        = "package_container";
    public static final String VERIFICATION_CODE                        = "verification_code";
    public static final String OLD_PASSWORD                             = "old_password";
    public static final String PASSWORD_CONFIRMATION                    = "password_confirmation";
    public static final String EMAIL                                    = "email";
    public static final String TIME_FROM                                = "time_from";
    public static final String TIME_TO                                  = "time_to";
    public static final String SCHEDULE                                 = "schedule";
    public static final String CITY_ID                                  = "city_id";
    public static final String TYPE                                     = "type";
    public static final String UNIT                                     = "unit";
    public static final String BUILDING                                 = "building";
    public static final String STREET_NUMBER                            = "street_number";
    public static final String STREET                                   = "street";
    public static final String VILLAGE                                  = "village";
    public static final String BARANGAY_ID                              = "barangay_id";
    public static final String ZIPCODE                                  = "zipcode";
    public static final String ADDRESS_TYPE                             = "address_type";
    public static final String ADDRESS_ID                               = "address_id";
    public static final String CONSUMER_ID                              = "consumer_id";
    public static final String CONTACT_PERSON                           = "contact_person";
    public static final String CONTACT_PERSON_NUMBER                    = "contact_person_number";
    public static final String IS_PRIMARY                               = "is_primary";
    public static final String TITLE                                    = "title";
    public static final String CONTENT                                  = "content";
    public static final String BOOKING_NUMBER                           = "booking_number";
    public static final String QR_IMAGE                                 = "qr_image";
    public static final String BIRTHDATE                                = "birthdate";
    public static final String GENDER                                   = "gender";
    public static final String ADDRESS_TAG                              = "addressTag";
}
